version: "3.9"

services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    volumes:
      - ./app:/app
    environment:
      - QDRANT_HOST=qdrant
    restart: always

volumes:
  qdrant_data:
